### ISSUE TITLE
Sinhala Language not support

### ISSUE THREAD

**Issue by thimiraonline** [gmfmi/ghost-easybar#1]
My native language, Sinhala is not supporting. Did you fix that?

**Comment by thimiraonline** [comment]
@gmfmi any update?

**Comment by gmfmi** [comment]
Hi @thimiraonline, sorry I didn't informed you. The issue is not coming from this repository but from searchinghost.

Soon, I will fix it in searchinghost and them upgrade the version in here.

**Comment by thimiraonline** [comment]
Please let me know when it is done.

**Comment by gmfmi** [comment]
I made the necessary in the searchinghost repo. To make it works on your theme, add this new `indexOptions` to your Ghost EasyBar configuration:

```js
new GhostEasyBar({
    contentApiKey: '...'
    ...,
    indexOptions: {
        encode: false,
        split: /\s+/
    }
});
```
